databases:
  - name: paradisefmx-db
    plan: free
    databaseName: paradisefmx
    user: paradisefmx

services:
  - type: web
    name: paradisefmx
    plan: free
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn paradisefmx.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: paradisefmx-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
